gluc_human = """
             MKSIYFVAGLFVMLVQGSWQRSLQDTEEKSRSFSASQADPL
             SDPDQMNEDKRHSQGTFTSDYSKYLDSRRAQDFVQWLMNTK
             RNRNNIAKRHDEFERHAEGTFTSDVSSYLEGQAAKEFIAWL
             VKGRGRRDFPEEVAIVEELGRRHADGSFSDEMNTILDNLAA
             RDFINWLIQTKITDRK"""

for residue in "ACDEFGHIKLMNPQRSTVWY":
    print(residue, gluc_human.count(residue))
