dna_seq = """AAGACGCAATAGGACTTTCACACCAAAGGTGGTCGGGGGACTCTAGCG
             AGCGCGTGATTGGACACGATAATGAAGCACTAATGCATATACCATGGG
             AGACGCCATAACGGGTCACTTCCCCGTCTGTTCCGGTCGCACACGCGT
             ATCGAGAACGGTTGTTCACTGTTAGAATTATGTAATTCGTACTACGCA
             TGCGGAACGGCATCATGCCTCAACATAGGCGAACGTCGTGACTGCGGA
             GGTGTGAGTT"""

print(dna_seq.count("TTC"))